### ISSUE TITLE
[SYCL-CTS] The CTS selector queries name for vendor, instead of simply vendor

### ISSUE THREAD

**Issue by Ruyk** [KhronosGroup/SYCL-CTS#13]
The snippet below shows what I think its an obvious typo:

https://github.com/KhronosGroup/SYCL-CTS/blob/7e469d115df4326b4683dd7ce200d1230ff27014/tests/common/cts_selector.h#L100-L101

If everyone agrees it is a typo, we can submit an MR with a fix.

**Comment by bader** [comment]
I agree.

I think SYCL specification also has a typo:

Platform descriptors | Return type | Description
-- | -- | --
info::platform::name | string_class | Returns the **_device_** name of this SYCL platform.
info::platform::vendor | string_class | Returns the vendor of this SYCL platform.

What is "the **_device_** name of this SYCL platform"?
Shouldn't it be "the name of this SYCL platform"?

**Comment by Ruyk** [comment]
Yes, that seems like a copy-paste error. Should be "the name of this SYCL platform"
