### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by cmc-rep** [KhronosGroup/SYCL-CTS#176]
How do I set the cmake options on a machine with oneapi base kit installed under /opt/intel/oneapi

cmake .. -DOpenCL_FOUND=True -DOpenCL_LIBRARY=/usr/lib/x86_64-linux-gnu
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at cmake/FindOpenCLTargets.cmake:27 (message):
  Use the official FindOpenCL module if CMake <3.7 support can be dropped
Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)

-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu (found version "2.2")
-- Found OpenCLTargets: /usr/include
-- Found PythonInterp: /opt/intel/oneapi/intelpython/latest/bin/python3 (found suitable version "3.7.10", minimum required is "3")
**CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find ComputeCpp (missing: ComputeCpp_EXECUTABLE
  ComputeCpp_LIBRARIES ComputeCpp_INCLUDE_DIRS)**
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindComputeCpp.cmake:24 (find_package_handle_standard_args)
  cmake/AddSYCLExecutable.cmake:13 (find_package)
  CMakeLists.txt:26 (include)

**Comment by bader** [comment]
@cmc-rep, please, set `-DSYCL_IMPLEMENTATION=Intel_SYCL` to use Intel oneAPI DPC++ implementation. By default, CMake files configure ComputeCPP implementation.

FYI, there is a pull request to rename `Intel_SYCL` to `DPCPP` - https://github.com/KhronosGroup/SYCL-CTS/pull/175.

**Comment by psalz** [comment]
Also, if the `dpcpp` compiler executable is not in your PATH, you may need to set ` -DINTEL_SYCL_ROOT=/opt/intel/oneapi` (and possibly more, not sure what the installation structure of the oneAPI base kit is).

**Comment by bader** [comment]
@cmc-rep, can we close that issue?

**Comment by bader** [comment]
> @cmc-rep, please, set `-DSYCL_IMPLEMENTATION=Intel_SYCL` to use Intel oneAPI DPC++ implementation. By default, CMake files configure ComputeCPP implementation.
> 
> FYI, there is a pull request to rename `Intel_SYCL` to `DPCPP` - #175.

@cmc-rep, this should fix the problem with the build.
I'm closing this issue. Feel free to re-open if you still have issues.
