### ISSUE TITLE
Build reduction  failed

### ISSUE THREAD

**Issue by malixian** [KhronosGroup/SYCL-CTS#215]
The project in branch SYCL-2020 is builed by command: 

> cmake -DCMAKE_BUILD_TYPE=Debug -DSYCL_IMPLEMENTATION=DPCPP  -DDPCPP_TARGET_TRIPLES=amdgcn-amd-amdhsa -DDPCPP_INSTALL_DIR=/my/llvm/build/  -DOpenCL_INCLUDE_DIR=/my/llvm/build/include/sycl/  -DOpenCL_LIBRARY=/my/llvm/build/lib/libOpenCL.so ..

Then, I want to test reduction. But it is builded failed with command : make -j 8 test_reduction.
Is there any problem about intel/llvm version?
The build failed log: 

> /home/shaoen/mlx/SYCL-CTS-Debug/tests/reduction/reduction_without_identity_param_fp64.cpp:38:40: error: reference to 'without_property' is ambiguous
>     run_tests_for_all_functors<double, without_property>()(range, queue, log,
>                                        ^
> /home/shaoen/mlx/SYCL-CTS-Debug/tests/reduction/reduction_without_identity_param_common.h:56:7: note: candidate found by name lookup is 'reduction_without_identity::without_property'
> using without_property = std::false_type;
>       ^
> /home/shaoen/mlx/SYCL-CTS-Debug/tests/reduction/reduction_common.h:20:16: note: candidate found by name lookup is 'reduction_common::without_property'
> constexpr bool without_property{false};
>                ^
> /home/shaoen/mlx/SYCL-CTS-Debug/tests/reduction/reduction_without_identity_param_fp64.cpp:38:40: error: reference to 'without_property' is ambiguous
>     run_tests_for_all_functors<double, without_property>()(range, queue, log,
>                                        ^
> /home/shaoen/mlx/SYCL-CTS-Debug/tests/reduction/reduction_without_identity_param_common.h:56:7: note: candidate found by name lookup is 'reduction_without_identity::without_property'
> using without_property = std::false_type;
>       ^
> /home/shaoen/mlx/SYCL-CTS-Debug/tests/reduction/reduction_common.h:20:16: note: candidate found by name lookup is 'reduction_common::without_property'
> constexpr bool without_property{false};
>                ^
> /home/shaoen/mlx/SYCL-CTS-Debug/tests/reduction/reduction_without_identity_param_fp64.cpp:40:40: error: reference to 'with_property' is ambiguous
>     run_tests_for_all_functors<double, with_property>()(nd_range, queue, log,
>                                        ^
> /home/shaoen/mlx/SYCL-CTS-Debug/tests/reduction/reduction_without_identity_param_common.h:55:7: note: candidate found by name lookup is 'reduction_without_identity::with_property'
> using with_property = std::true_type;
> .....
> too many error，not shown....

**Comment by psalz** [comment]
I haven't looked into this error specifically, but I can tell you that this is at least somewhat expected, as none of the supported SYCL implementations have fully implemented the 2020 specification yet, so not all test cases compile for all implementations. The CTS contains [a set of filter files](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/ci) that lists all tests that do *not* compile for a given SYCL implementation and version that is used for our continuous integration. [For DPCPP that is currently revision f5c838cd](https://github.com/KhronosGroup/SYCL-CTS/blob/65856bfb5844fc73f1c4e0841bf4be4c6028eef9/.github/workflows/build_ci_containers.yml#L44) and you can see that the filter does include the reduction tests. However that revision is 2 months old at this point, and I believe the filter is thus somewhat outdated (cc @bader).

**Comment by vasilytric** [comment]
@malixian  `error: reference to 'without_property' is ambiguous` will be fixed by this PR: [KhronosGroup/SYCL-CTS/PR#206](https://github.com/KhronosGroup/SYCL-CTS/pull/206)

**Comment by bader** [comment]
> I haven't looked into this error specifically, but I can tell you that this is at least somewhat expected, as none of the supported SYCL implementations have fully implemented the 2020 specification yet, so not all test cases compile for all implementations. The CTS contains [a set of filter files](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/ci) that lists all tests that do _not_ compile for a given SYCL implementation and version that is used for our continuous integration. [For DPCPP that is currently revision f5c838cd](https://github.com/KhronosGroup/SYCL-CTS/blob/65856bfb5844fc73f1c4e0841bf4be4c6028eef9/.github/workflows/build_ci_containers.yml#L44) and you can see that the filter does include the reduction tests. However that revision is 2 months old at this point, and I believe the filter is thus somewhat outdated (cc @bader).

One more note: @malixian is compiling for `amdgcn-amd-amdhsa` target triple and I think target triple might impact the compilation result (success/fail). The results for DPC++ mentioned by @psalz were gathered with default target triple compilation (i.e. `spir64`).

@AerialMantis, FYI.

**Comment by AerialMantis** [comment]
We've not run the SYCL-CTS for the DPC++ HIP backend yet so I'm not sure exactly how much of it will pass with the `amdgcn-amd-amdhsa` triple, though I expect the reductions will not work atm as there are missing built-in functions which reductions require.

**Comment by bader** [comment]
As @AerialMantis, mentioned DPC++ implementation doesn't support reductions on HIP platform.
@malixian, feel free to open a feature request for DPC++ to support reductions on AMD devices.
I suggest we close this issue. Any objections?
