### ISSUE TITLE
Introducing new tests *.exe-files architecture

### ISSUE THREAD

**Issue by vasilytric** [KhronosGroup/SYCL-CTS#219]
Hi all,

After building some test we have only one `*.exe`-file for each test group (exceptions, buffer, etc.), but test for `kernel_bundle` required few `*.exe`-files due to we must have stricted set of kernels in the application.
For example: test for `get_kernel_ids_multiple_kernels`, `get_kernel_ids_single_kernel` and `get_kernel_ids_no_kernels`
should contained in separate `*.exe`-file due to `get_kernel_ids` function couldn't chose which kernel should use and which kernel should be ignored
Building process:
if we will use `make test_kernel_bundle` then will be builded all tests, except tests, that mentioned in `independent_cases_list` in the the [tests/kernel_bundle/CMakeLists.txt](https://github.com/KhronosGroup/SYCL-CTS/pull/218/files#diff-04b8efb2d8207d0e355e4dd00fc039f913bda2e96800fdd981639bcfc325ca2c) file.
for build this tests need call building process for each test separately: `make test_get_kernel_ids_multiple_kernels`, `make test_get_kernel_ids_single_kernel` and `make test_get_kernel_ids_no_kernels`
But if use `make` all tests will be builded

Some tests for `kernel_bundle` thematic can be found here: KhronosGroup/SYCL-CTS PR https://github.com/KhronosGroup/SYCL-CTS/pull/218

**Comment by bader** [comment]
All new tests are built by default and executed by `run_conformance_tests.py` script. The issue seems to be implemented by #218 and can be closed as done.

**Comment by gmlueck** [comment]
Closing based on @bader's description above.
