### ISSUE TITLE
Is `platform()` forced to return a host platform?

### ISSUE THREAD

**Issue by TApplencourt** [KhronosGroup/SYCL-CTS#278]
Hi,

In SYCL2020, the default constructor of the platform returns an instance that is a copy of the platform which contains the device returned by `default_selector_v`. (https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#_platform_interface)

Hence I think we should change this [tests](https://github.com/KhronosGroup/SYCL-CTS/blob/f8d877560d82e2e4a7eacefe9d252178a7d602c1/tests/platform/platform_constructors.cpp#L35) in the CTS? Or maybe the cts hijack `default_selector_v`  to always be a host device. 

I can try to make my first PR to CTS if you agree that tests need to be updated. 

Regards,
Thomas

**Comment by keryell** [comment]
That makes sense.
