### ISSUE TITLE
error: DisableFTZ needs an implentation

### ISSUE THREAD

**Issue by linuxcpp6** [KhronosGroup/SYCL-CTS#323]
when build,error:

error: ForceFTZ needs an implentation

error: DisableFTZ needs an implentatio

nerror: RestoreFPState needs an implementation

Why is it?

**Comment by bader** [comment]
@TechnologyAndEducation, sorry for the delay.
Could you provide the compiler version you use to build SYCL-CTS and what compiler options are used, please?
GitHub Actions CI builds SYCL-CTS using three different compilers and all tests build fine except the list from the corresponding filter - https://github.com/KhronosGroup/SYCL-CTS/tree/SYCL-2020/ci.

**Comment by gmlueck** [comment]
Closing this for now because we can't reproduce it.  Please reopen if you want to discuss further.
