### ISSUE TITLE
Does `OpenCL` is really required?

### ISSUE THREAD

**Issue by TApplencourt** [KhronosGroup/SYCL-CTS#347]
Hi,

https://github.com/KhronosGroup/SYCL-CTS/blob/94a4b36923a730a1999f899bdb8bef1804ffee05/CMakeLists.txt#L12

Does OpenCL is really required?

I try to build the CTS on a system where OpenCL is not available.

**Comment by ProGTX** [comment]
SYCL 1.2.1 requires OpenCL. SYCL 2020 doesn't, OpenCL is just one possible backend, but I believe there is still work left to generalize the CTS.

**Comment by psalz** [comment]
I believe the main reason for still having this dependency is the [reference_math](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/oclmath/reference_math.cpp) implementation, which uses OpenCL types all over the place (which makes sense, as it originally comes from the [OpenCL CTS](https://github.com/KhronosGroup/OpenCL-CTS/blob/main/test_conformance/math_brute_force/reference_math.cpp)).

**Comment by TApplencourt** [comment]
Look like reference_maths only require the OpenCL Headers. 

One should try to verify if this is really the case. If it's so, one should update the cmake to distinguish between the requirement of OpenCL header and OpenCL libs.
