### ISSUE TITLE
Incorrect usage of half data type?

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/SYCL-CTS#37]
If I understand correctly, SYCL 1.2.1 specification doesn't define `cl::sycl::half` data type and only defines `cl::sycl::cl_half` data type.

However, the former is used a lot across SYCL CTS tests. Could please someone help to understand if it is a bug of SYCL CTS or SYCL 1.2.1 spec?

[this search query](https://github.com/KhronosGroup/SYCL-CTS/search?q=cl%3A%3Asycl%3A%3Ahalf&unscoped_q=cl%3A%3Asycl%3A%3Ahalf) shows 29 results, but some of them are incorrect, so, there is only ~15 places where `cl::sycl::half` is used.

**Comment by AlexeySachkov** [comment]
Related spec issue: KhronosGroup/SYCL-Docs#40

**Comment by keryell** [comment]
Discussed during Tuesday 2020/02/18 meeting
- half does not exist in C++
- Related to https://github.com/KhronosGroup/SYCL-Docs/issues/40
  - Need to be discussed there first.

**Comment by keryell** [comment]
Is it solved by https://github.com/KhronosGroup/SYCL-CTS/pull/154?

**Comment by AlexeySachkov** [comment]
> Is it solved by #154?

Yes, I think so, thanks!
