### ISSUE TITLE
Evaluate current CTS coverage

### ISSUE THREAD

**Issue by sbalint98** [KhronosGroup/SYCL-CTS#385]
## Background
An accurate picture of the current coverage is essential to prioritize a breadth-first approach for further enhancement of the CTS. Currently, there is no detailed description of the exact feature coverage of the CTS. 

## Proposed approach
We intend to produce a preliminary feature list using scripts, which are subsequently hand-verified by developers. We will pay special attention to Chapter 4 of the CTS and Appendix B during this process. We plan on analyzing the already existing development plans to get insight into the required level of coverage.

Can you please highlight additional resources and parts of the specification that we should consider?

## Output
We will share an excel sheet with the estimated level of coverage for each section of the considered part of the specification.

**Comment by bibrakc** [comment]
Weekly status update on the SYCL-CTS assessment can be found in the sheet below:

[SYCL CTS Assessment Update 1.xlsx](https://github.com/KhronosGroup/SYCL-CTS/files/9880365/SYCL.CTS.Assessment.Update.1.xlsx)

**Comment by bibrakc** [comment]
Weekly status update: Second draft of the SYCL-CTS assessment can be found in the sheet below:
[SYCL CTS Assessment Update 2.xlsx](https://github.com/KhronosGroup/SYCL-CTS/files/9930377/SYCL.CTS.Assessment.Update.2.xlsx)

**Comment by aleksmesh** [comment]
Our team is now working on the accessors test coverage, after which we plan to cover the group algorithms.

**Comment by aleksmesh** [comment]
@AJcodes We haven't started implementing tests for group algorithms yet, so we leave it to you then. We also have plans to cover default async handler next.

**Comment by AJcodes** [comment]
@aleksmesh Could we perhaps have a separate call to sync on what your team's plans are? We've compiled a work plan of our own to cover the SYCL2020 features, so it would be good if we're aligned

**Comment by aleksmesh** [comment]
@AJcodes Sure we can. Please submit meeting.

**Comment by AJcodes** [comment]
@aleksmesh I sent a google calendar invite for today, 4pm CET, but just remembered you might be in a different time zone. Would that work for you or should I reschedule (our team is based in Europe, hence CET)?

**Comment by aleksmesh** [comment]
@AJcodes Hello! I can not find the sent invite in the mail. Where did you send it? Could you send it to alekseix.meshkov@intel.com?
And my timezone is UTC+2.

**Comment by AJcodes** [comment]
@aleksmesh I've sent another Google Calendar invite to your email for tomorrow, 11am UTC+1. Do you see it this time?

**Comment by aleksmesh** [comment]
@AJcodes  Yes I do. Thank you!

**Comment by gmlueck** [comment]
Contract has finished.  Closing.
