### ISSUE TITLE
hierarchical_implicit_reduce test is disabled due to return at the very first line

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/SYCL-CTS#46]
https://github.com/KhronosGroup/SYCL-CTS/blob/806294de8e9e69fe0057432f3c4fdb668b12db0b/tests/hierarchical/hierarchical_implicit_reduce.cpp#L150-L154

**Comment by keryell** [comment]
Discussed during 2020/02/18 meeting: Intel & Codeplay to look at it
