### ISSUE TITLE
Reduce duplicate code in tests for `sycl::item`

### ISSUE THREAD

**Issue by nolmoonen** [KhronosGroup/SYCL-CTS#491]
The one-, two-, and three-dimensional tests for `sycl::item` in `tests/item/item_1d.cpp`, `tests/item/item_2d.cpp`, and `tests/item/item_3d.cpp` have a lot of code in common. This common code should be factored out. The tests for the other multidimensional classes can serve as an example of how this can be done (`id`, `range`, `nd_range`, `nd_item`).

**Comment by bader** [comment]
@aleksmesh, thanks a lot for fixing this.
