### ISSUE TITLE
Improve ranges and index space identifiers tests

### ISSUE THREAD

**Issue by nolmoonen** [KhronosGroup/SYCL-CTS#498]
Several tests for the ranges and index space identifiers launch a kernel which returns a single status code indicating whether the test passed or failed. This is suboptimal, as it does not help the user in identifying which specific member function is not conforming. Examples of this are `h_item/h_item_api.cpp`, `item/item_(1|2|3)d.cpp`, and `nd_item/nd_item_api.cpp`, perhaps others as well.

A better solution could be to return an array of status codes (`group/group_api.cpp` or `range/range_api.cpp`) or to use multiple independent kernel launches (`id/id.cpp`). Perhaps these approaches can be consolidated as well.

**Comment by AmirIpma** [comment]
Started working with on this issue

**Comment by AmirIpma** [comment]
@nolmoonen Patch was merged, could we close this issue?
