### ISSUE TITLE
Provide prebuild binaries

### ISSUE THREAD

**Issue by qarmin** [KhronosGroup/SYCL-CTS#543]
I tried to compile code from this repository several times, but each time I found new problems and I have neither the time nor the will to fix it.
Latest error is
```
/home/rafal/test/SYCL-CTS/util/../tests/common/common.h:25:10: fatal error: 'sycl/sycl.hpp' file not found
#include <sycl/sycl.hpp>
         ^~~~~~~~~~~~~~~
1 error generated.
gmake[2]: *** [util/CMakeFiles/util.dir/build.make:76: util/CMakeFiles/util.dir/aspect_set.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1733: util/CMakeFiles/util.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

With prebuild binaries I would not have such problems.

I see that already CI produces build times, but also could upload produced binaries.

**Comment by keryell** [comment]
What would you use the binaries for?
What is your use case?

**Comment by psalz** [comment]
That error might indicate that the SYCL implementation is not detected correctly by our CMake setup. What SYCL implementation and version are you using?

**Comment by gmlueck** [comment]
Closing for now.  Please reopen if you want to discuss further.
