### ISSUE TITLE
Using `sycl::half` in functions like `std::floor` is ambiguous 

### ISSUE THREAD

**Issue by nilsfriess** [KhronosGroup/SYCL-CTS#559]
In [some places](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/util/math_reference.cpp#L493), `std` functions that have overloads for both `float` and `double` are called with `sycl::half` arguments. In OpenSYCL, we provide conversion operators for `half -> float` and `half -> double` which then leads to errors like `error: call to 'floor' is ambiguous`. 

The SYCL spec is a bit vague w.r.t. the `half` class, but I think implementing conversion operators for both `float` and `double` is valid, so maybe explicit casts should be added when calling `std::floor`, `std::fmin` etc. with `half` arguments. What do you think?

**Comment by fraggamuffin** [comment]
need sycl::half spec in 2020
also needed for CTS , needed for regular arithmetic conversions

**Comment by gmlueck** [comment]
DPC++ has an extension for bfloat16 which might serve as a model for the operations that we should support for `sycl::half`.  Here is the bfloat16 extension specification:

https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_bfloat16.asciidoc

**Comment by keryell** [comment]
I have the feeling we could solve the problem in the spec with
```c++
template <typename T>
requires (the right types)
operator T() { ... }
template <typename T>
requires (the right types)
half(T v) { ... }
```
