### ISSUE TITLE
Build error on enabling accessor implicit conversion tests

### ISSUE THREAD

**Issue by mmoadeli** [KhronosGroup/SYCL-CTS#622]
Below message is at the top of `accessor_implicit_conversion_core.cpp` and a number of other implicit conversion files.
```
// FIXME: re-enable when sycl::accessor is implemented
// Issue link https://github.com/intel/llvm/issues/8298
```
The [Issue 8298](https://github.com/intel/llvm/issues/8298) is already addressed. An attempt to enable the tests by modifying file as below:
```
* !defined(__SYCL_COMPILER_VERSION) -> defined(__SYCL_COMPILER_VERSION)
* DISABLED_FOR_TEST_CASE(hipSYCL, ComputeCpp, DPCPP) -> DISABLED_FOR_TEST_CASE(hipSYCL, ComputeCpp) // line 29
```
showed two main build errors (there are other ones which seem to be fixed once the below two are addressed):
* accessor_implicit_conversions.h:81:5: error: no matching constructor for initialization of 'Catch::SectionInfo' SECTION(
* accessor_implicit_conversions.h:90:30: error: unknown type name 'DataT', using SrcDataT = const DataT;

**Comment by aleksmesh** [comment]
@mmoadeli It is fixed in PR [#593](https://github.com/KhronosGroup/SYCL-CTS/pull/593).
