### ISSUE TITLE
Using ComputeCPP in GitHub Actions CI.

### ISSUE THREAD

**Issue by bader** [KhronosGroup/SYCL-CTS#755]
According to https://codeplay.com/portal/news/2023/07/07/the-future-of-computecpp, there will be no support for ComputeCpp starting September 1 2023. Considering that ComputeCpp won't be able to pass all conformance tests by that time, I suggest we remove compilation with ComputeCpp in CI and clean-up conditional compilation configured for ComputeCpp.

**Comment by psalz** [comment]
Shouldn't we just drop ComputeCpp from the CTS completely? I.e., CMake, `DISABLE_FOR_TEST_CASE(ComputeCpp)`, etc?

**Comment by bader** [comment]
> Shouldn't we just drop ComputeCpp from the CTS completely? I.e., CMake, `DISABLE_FOR_TEST_CASE(ComputeCpp)`, etc?

Yes, that's what I mean.

**Comment by fraggamuffin** [comment]
stop building CTS with computecpp?, cmake configuration removal? everything, all flags, mention of cmake, need to confirm

**Comment by AerialMantis** [comment]
@bader I can confirm that we are okay with ComputeCpp support in the GitHub CI being dropped and any ComputeCpp-specific workarounds being removed.

**Comment by fraggamuffin** [comment]
closing
