### ISSUE TITLE
New builtin guarantees should be covered by the builtins tests

### ISSUE THREAD

**Issue by steffenlarsen** [KhronosGroup/SYCL-CTS#761]
With the clarifications to the SYCL builtins in https://github.com/KhronosGroup/SYCL-Docs/pull/428 and https://github.com/KhronosGroup/SYCL-Docs/pull/440, the builtins now make additional guarantees about how they can be used. These additional guarantees should be tested.

Tentative list of additional test cases:
1. Tests for swizzle to vector implicit conversion when used in a vector builtin.
2. Tests for implicit conversion of arguments for non-templated overloads.
3. Tests for explicit template instantiations for templated overloads.

**Comment by fraggamuffin** [comment]
should not write these tests until we approve #440

**Comment by fraggamuffin** [comment]
we mean this one:
https://github.com/KhronosGroup/SYCL-Docs/pull/440
