### ISSUE TITLE
Bump hipSYCL version and regenerate filters

### ISSUE THREAD

**Issue by psalz** [KhronosGroup/SYCL-CTS#796]
We haven't updated the hipSYCL version used in CI for over a year ([3d8b1cd ](https://github.com/KhronosGroup/SYCL-CTS/blob/c6711e6dc6c970a374c03a3e2a55b01383991656/.github/workflows/cts_ci.yml#L61C22-L61C29) is from [January 2022](https://github.com/OpenSYCL/OpenSYCL/commit/3d8b1cd)).

We then should [regenerate](https://github.com/KhronosGroup/SYCL-CTS/blob/282acab13ce78bbbeca5a4fac96eeda88f18514a/ci/generate_exclude_filter.py) the CI filters for hipSYCL as well. Although one problem we have here is that presumably most of the tests are compile-time disabled for hipSYCL, and we currently don't have a good way of figuring out which ones we can re-enable...

**Comment by nilsfriess** [comment]
Hi, I'm working on the AdaptiveCpp (aka hipSYCL) project and I'd like to help on this. I actually did some work a while ago to fix some issues that caused tests to not compile/ fail in AdaptiveCpp but never really made an effort to update the AdaptiveCpp/hipSYCL version used in the CTS's CI. I'll try to see if I can regenerate the filters file on a test system and report back to you. Likely some tests will not compile/pass anymore but I think it would still be good to have a recent version in CI that can then be updated more often. 

I will also probably open a PR soon-ish to update at least the CMake configuration to the new name.

**Comment by psalz** [comment]
Wait, I'm *right now* in the process of renaming hipSYCL to AdaptiveCpp everywhere and updating the CI filter! 😅 I'll open a PR (hopefully) within the hour.

**Comment by nilsfriess** [comment]
I haven't started yet, so all good ;)
