### ISSUE TITLE
`marray` test does not test everything (or anything?) on device

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/SYCL-CTS#821]
Maybe I'm missing something as I haven't reviewed the whole test, but here is at least one code path which I've traced:

https://github.com/KhronosGroup/SYCL-CTS/blob/eec8701491114d1930c90679ba5072dd2a5162cb/tests/marray/marray_operators_core.cpp#L29-L32

Which brings us to:

https://github.com/KhronosGroup/SYCL-CTS/blob/eec8701491114d1930c90679ba5072dd2a5162cb/tests/marray/marray_operators.h#L482-L486

Then:

https://github.com/KhronosGroup/SYCL-CTS/blob/eec8701491114d1930c90679ba5072dd2a5162cb/tests/marray/marray_operators.h#L150-L155

And finally:

https://github.com/KhronosGroup/SYCL-CTS/blob/eec8701491114d1930c90679ba5072dd2a5162cb/tests/marray/marray_operators.h#L120-L133

From what I can see, there is no mention of queues or devices at all. Perhaps it is hidden somewhere deep in the helpers, but I don't think that it is the case. Looks more like we really only test `marray` functionality on host

**Comment by bader** [comment]
@AlexeySachkov is right. I think we can expect `run_unary_sequence` to run the test on the device, but it's not the case.
Similar approach is used by other tests e.g. atomic_ref. See base class in https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/tests/atomic_ref/atomic_ref_test_base.h and derivative classes to run specific tests defining `run_on_device` method (e.g. https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/tests/atomic_ref/atomic_ref_add_sub_op_all_types_test.h).

According to the [test plan](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/test_plans/math_array.asciidoc) the tests are supposed to be executed on the device.

Having said that, I don't expect marray implementation to be different on the host and SYCL devices. Unfortunately, the test doesn't check "device copyable" property neither.

**Comment by tomdeakin** [comment]
Awaiting a PR to fix this.
