### ISSUE TITLE
Ill-formed `if constexpr` branch in vector_operator CTS test for `sycl::vec<bool>`

### ISSUE THREAD

**Issue by uditagarwal97** [KhronosGroup/SYCL-CTS#896]
## Description
We have the following in the vector_operator test for `sycl::vec<bool>`, where the discarded branch of `if constexpr` is ill-formed - it is trying to increment `vec<bool>` which is not allowed by the SPEC.
```
if constexpr (!std::is_same_v<bool, bool>) {
      for (int i = 0; i < 1; ++i) {
        resArr[i] = static_cast<bool>(1);
      }
      for (int i = 0; i < 1; ++i) {
        resArr2[i] = static_cast<bool>(1) + static_cast<bool>(1);
      }
      testVec1Copy = testVec1;
      resVec = testVec1Copy++; // <------------------- Error
```
C++ requires that `Outside a template, a discarded statement is fully checked. if constexpr is not a substitute for the #if preprocessing directive:` https://en.cppreference.com/w/cpp/language/if

Faulty CTS test: https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/tests/vector_operators/generate_vector_operators.py#L212

**Comment by uditagarwal97** [comment]
@gmlueck FYI

**Comment by aelovikov-intel** [comment]
Looks like it might have been fixed by https://github.com/KhronosGroup/SYCL-CTS/pull/870.
